var vocab = 
[
	{
	semester: "fall 2017", 
	module: "1.1",
	vocab: [
		{type: "adjective", plain: "おいしい", english:	"delicious"}, 
		{type: "noun", plain: "さかな", english:	"fish"}, 
		{type: "noun", plain: "にく", english:	"meat"}, 
		{type: "noun", plain: "やさい", english:	"vegetable"}, 
		{type: "noun", plain: "メニュー", english:	"menu"}, 
		{type: "noun", plain: "えいが", english:	"movie"}, 
		{type: "noun", plain: "どくしょ", english:	"reading"}, 
		{type: "noun", plain: "スポーツ", english:	"sports"}, 
		{type: "noun", plain: "ダンス", english:	"dance"}, 
		{type: "noun", plain: "ゲーム", english:	"game"}, 
		{type: "noun", plain: "アニメ", english:	"anime"}, 
		{type: "noun", plain: "まんが", english:	"manga"}, 
		{type: "noun", plain: "ひと", english:	"person"}, 
		{type: "noun", plain: "しゅくだい", english:	"homework"}, 
		{type: "noun", plain: "いぬ", english:	"dog"}, 
		{type: "noun", plain: "ねこ", english:	"cat"}, 
		{type: "adjective", plain: "たかい", english:	"expensive;high"}, 
		{type: "phrase", plain: "〜えん", english:	"...yen"}, 
		{type: "adjective", plain: "やすい", english:	"inexpensive; cheap"}, 
		{type: "phrase", plain: "〜ドル", english:	"...dollar(s)"}, 
		{type: "phrase", plain: "いくら", english:	"how much"}
		]
	}, 
	{
	semester: "fall 2017", 
	module: "1.2",
	vocab: [
		{type: "", plain: "カフェ", english: "cafe"},
		{type: "", plain: "としょかん", english: "library"},
		{type: "", plain: "ぎんこう", english: "bank"},
		{type: "", plain: "トイレ", english: "toilet; restroom"},
		{type: "", plain: "りょう", english: "dormitory"},
		{type: "", plain: "アパート", english: "apartment"},
		{type: "", plain: "えんぴつ", english: "pencil"},
		{type: "", plain: "とけい", english: "watch; clock"},
		{type: "", plain: "かさ", english: "umbrella"},
		{type: "", plain: "ぼうし", english: "hat; cap"},
		{type: "", plain: "かばん", english: "bag"},
		{type: "", plain: "ほん", english: "book"},
		{type: "", plain: "くつ", english: "shoes"},
		{type: "", plain: "Tシャツ", english: "T-shirt"},
		{type: "", plain: "さいふ", english: "wallet"},
		{type: "", plain: "ジーンズ", english: "jeans"},
		{type: "", plain: "じしょ", english: "dictoinary"},
		{type: "", plain: "ノート", english: "notebook"},
		{type: "", plain: "じてんしゃ", english: "bicycle"},
		{type: "", plain: "ペン", english: "pen"}
	]
	},
	{
	semester: "fall 2017", 
	module: "2.1",
	vocab: [
		{type: "verb", plain: "いく", english: "to go"},
		{type: "verb", plain: "のむ", english: "to drink"},
		{type: "verb", plain: "かえる", english: "to go back"},
		{type: "verb", plain: "はなす", english: "to speak"},
		{type: "verb", plain: "きく", english: "to listen"},
		{type: "verb", plain: "よむ", english: "to read"},
		{type: "verb", plain: "おきる", english: "to get up"},
		{type: "verb", plain: "ねる", english: "to sleep; go to bed"},
		{type: "verb", plain: "たべる", english: "to eat"},
		{type: "verb", plain: "みる", english: "to watch; look; see"},
		{type: "verb", plain: "あびる", english: "to take (a shower)"},
		{type: "verb", plain: "する", english: "to do"},
		{type: "verb", plain: "べんきょうする", english: "to study"},
		{type: "verb", plain: "くる", english: "to come"},
		{type: "", plain: "ごはん", english: "meal; cooked rice"},
		{type: "", plain: "おちゃ", english: "green tea"},
		{type: "", plain: "おさけ", english: "sake; alcohol"},
		{type: "", plain: "みず", english: "water"},
		{type: "", plain: "コーヒー", english: "coffee"},
		{type: "", plain: "いつ", english: "when"},
		{type: "", plain: "あさ", english: "morning"},
		{type: "", plain: "ひる", english: "afternoon"},
		{type: "", plain: "ばん", english: "evening"},
		{type: "", plain: "きょう", english: "today"},
		{type: "", plain: "きのう", english: "yesterday"},
		{type: "", plain: "あした", english: "tomorrow"},
		{type: "", plain: "あさって", english: "day after tomorrow"},
		{type: "", plain: "おととい", english: "day before yesterday"}
	]
	},
	{
	semester: "fall 2017", 
	module: "2.2",
	vocab: [
		{type: "", plain: "テレビ", english: "TV"},
		{type: "", plain: "デート", english: "date (romantic)"},
		{type: "", plain: "れんしゅう", english: "practice"},
		{type: "", plain: "シャワー", english: "shower"},
		{type: "", plain: "がっこう", english: "school"},
		{type: "", plain: "きょうかい", english: "church"},
		{type: "", plain: "へや", english: "room"},
		{type: "", plain: "きょうしつ", english: "classroom"},
		{type: "", plain: "いえ", english: "house; home"},
		{type: "", plain: "うち", english: "home; house"},
		{type: "", plain: "こんしゅう", english: "this week"},
		{type: "", plain: "こんばん", english: "tonight"},
		{type: "", plain: "まいにち", english: "everyday"},
		{type: "", plain: "しゅうまつ", english: "weekend"},
		{type: "", plain: "いい", english: "good"},
		{type: "", plain: "おそい", english: "late"},
		{type: "", plain: "はやい", english: "early"},
		{type: "", plain: "たいへん", english: "tough (situation)"},
		{type: "", plain: "よく", english: "often; much"},
		{type: "", plain: "たいてい", english: "usually"},
		{type: "", plain: "ときどき", english: "sometimes"},
		{type: "", plain: "ちょっと", english: "a little"},
		{type: "", plain: "あまり", english: "not much"},
		{type: "", plain: "ぜんぜん", english: "not at all"},
		{type: "", plain: "いっしょに", english: "together"},
		{type: "", plain: "どうですか", english: "How about...?How is...?"}
	]
	},
	{
	semester: "fall 2017", 
	module: "3.1",
	vocab: [
		{type: "verb", plain: "あう", english:	"to meet; to see (a person)"},
		{type: "phrase", plain: "ある", english:	"there is..."},
		{type: "verb", plain: "かう", english:	"to buy"},
		{type: "verb", plain: "かく", english:	"to write"},
		{type: "verb", plain: "いる", english:	"(a person) is in..., stays at..."},
		{type: "verb", plain: "とる", english:	"to take (a picture)"},
		{type: "verb", plain: "まつ", english:	"to wait"},
		{type: "verb", plain: "わかる", english:	"to understand"},
		{type: "noun", plain: "かいもの", english:	"shopping"},
		{type: "noun", plain: "アルバイト", english:	"part-time job"},
		{type: "noun", plain: "いす", english:	"chair"},
		{type: "noun", plain: "テーブル", english:	"table"},
		{type: "noun", plain: "つくえ", english:	"desk"},
		{type: "noun", plain: "まど", english:	"window"},
		{type: "noun", plain: "ドア", english:	"door"},
		{type: "noun", plain: "しゃしん", english:	"picture; photograph"},
		{type: "noun", plain: "メール", english:	"e-mail"},
		{type: "noun", plain: "てがみ", english:	"letter"},
		{type: "noun", plain: "おかね", english:	"money"},
		{type: "noun", plain: "おみやげ", english:	"souvenir"},
		{type: "noun", plain: "こども", english:	"child"},
		{type: "noun", plain: "ひと", english:	"person"},
		{type: "noun", plain: "じかん", english:	"time"},
		{type: "noun", plain: "バス", english:	"bus"},
		{type: "adjective", plain: "みぎ", english:	"right"},
		{type: "adjective", plain: "ひだり", english:	"left"},
		{type: "adjective", plain: "まえ", english:	"front"},
		{type: "adjective", plain: "うしろ", english:	"back"},
		{type: "adjective", plain: "なか", english:	"inside"},
		{type: "adjective", plain: "そと", english:	"outside"},
		{type: "adjective", plain: "うえ", english:	"on; above"},
		{type: "adjective", plain: "した", english:	"under"},
		{type: "adjective", plain: "ちかく", english:	"near; nearby"},
		{type: "adjective", plain: "となり", english:	"next (same type)"},
		{type: "adjective", plain: "よこ", english:	"next"},
		{type: "adjective", plain: "あいだ", english:	"between"}
		]
	},
	{
	semester: "fall 2017", 
	module: "3.2",
	vocab: [
	{type: "", plain: "〜じかん", english: "hours (duration)"},
	{type: "", plain: "ねん", english: "year"},
	{type: "", plain: "せんしゅう", english: "last week"},
	{type: "", plain: "こんしゅう", english: "this week"},
	{type: "", plain: "らいしゅう", english: "next week"},
	{type: "", plain: "おてら", english: "temple"},
	{type: "", plain: "こうえん", english: "park"},
	{type: "", plain: "びょういん", english: "hospital"},
	{type: "", plain: "ほんや", english: "bookstore"},
	{type: "", plain: "まち", english: "town; city"},
	{type: "", plain: "スーパー", english: "supermarket"},
	{type: "", plain: "デパート", english: "department store"},
	{type: "", plain: "バスてい", english: "bus stop"},
	{type: "", plain: "ホテル", english: "hotel"},
	{type: "", plain: "レストラン", english: "restaurant"},
	{type: "", plain: "げつようび", english: "Monday"},
	{type: "", plain: "かようび", english: "Tuesday"},
	{type: "", plain: "すいようび", english: "Wednesday"},
	{type: "", plain: "もくようび", english: "Thursday"},
	{type: "", plain: "きんようび", english: "Friday"},
	{type: "", plain: "たんじょうび", english: "birthday"},
	{type: "", plain: "きのう", english: "yesterday"},
	{type: "", plain: "しつもん", english: "question"},
	{type: "", plain: "こたえ", english: "answer"},
	{type: "", plain: "しゅくだい", english: "homework"},
	{type: "", plain: "たんご", english: "vocabulary; word"},
	{type: "", plain: "ぐらい", english: "about (for duration)"},
	{type: "", plain: "ごめんなさい", english: "I'm sorry"},
	{type: "", plain: "だから", english: "so; therefore"},
	{type: "", plain: "たくさん", english: "many; a lot"},
	{type: "", plain: "どうして", english: "why"},
	{type: "", plain: "ひとりで", english: "alone"},
	{type: "", plain: "ほんとうですか", english: "Really?"},
	{type: "", plain: "から", english: "from"},
	{type: "", plain: "まで", english: "to; as far as"}
	]
	},
	{
	semester: "fall 2017", 
	module: "4.1",
	vocab: [
		{type: "", plain: "あたらしい", english: "new"},
		{type: "", plain: "あつい", english: "hot (air temperature)"},
		{type: "", plain: "いそがしい", english: "busy (people/day)"},
		{type: "", plain: "うるさい", english: "loud; noisy; annoying"},
		{type: "", plain: "おおきい", english: "big; large"},
		{type: "", plain: "おもしろい", english: "interesting; funny"},
		{type: "", plain: "かっこいい", english: "good-looking"},
		{type: "", plain: "きたない", english: "dirty; messy"},
		{type: "", plain: "こわい", english: "frightening; scary"},
		{type: "", plain: "さむい", english: "cold (air temperature)"},
		{type: "", plain: "たのしい", english: "fun"},
		{type: "", plain: "ちいさい", english: "small"},
		{type: "", plain: "つまらない", english: "boring"},
		{type: "", plain: "つめたい", english: "cold (thing to touch)"},
		{type: "", plain: "ふるい", english: "old (not used for people)"},
		{type: "", plain: "むずかしい", english: "difficult"},
		{type: "", plain: "やさしい", english: "easy (problem); kind (person)"},
		{type: "", plain: "かんたん(な)", english: "easy; simple"},
		{type: "", plain: "きらい(な)", english: "disgusted with; to dislike"},
		{type: "", plain: "きれい(な)", english: "beautiful; clean"},
		{type: "", plain: "げんき(な)", english: "healthy; energetic"},
		{type: "", plain: "しずか(な)", english: "quiet"},
		{type: "", plain: "すき(な)", english: "fond of; to like"},
		{type: "", plain: "だいきらい(な)", english: "to hate"},
		{type: "", plain: "だいすき(な)", english: "very fond of; to love"},
		{type: "", plain: "にぎやか(な)", english: "lively"},
		{type: "", plain: "ひま(な)", english: "not busy; to have a lot of free time"}
	]
	},
	{
	semester: "fall 2017", 
	module: "4.2",
	vocab: [
		{type: "", plain: "うみ", english: "sea; ocean"},
		{type: "", plain: "おとこのひと", english: "man"},
		{type: "", plain: "おんなのひと", english: "woman"},
		{type: "", plain: "かわ", english: "river"},
		{type: "", plain: "やま", english: "mountain"},
		{type: "", plain: "りょこう", english: "travel"},
		{type: "", plain: "きって", english: "postal stamps"},
		{type: "", plain: "きっぷ", english: "ticket"},
		{type: "", plain: "たべもの", english: "food"},
		{type: "", plain: "てんき", english: "weather"},
		{type: "", plain: "のみもの", english: "drink"},
		{type: "", plain: "のりもの", english: "ride; a means of transportatoin"},
		{type: "", plain: "はがき", english: "postcard"},
		{type: "", plain: "ひこうき", english: "airplane"},
		{type: "", plain: "でんしゃ", english: "train"},
		{type: "", plain: "おかね", english: "money"},
		{type: "", plain: "やすみ", english: "holiday; day off; absence"},
		{type: "", plain: "にもつ", english: "baggage"},
		{type: "", plain: "おふろ", english: "bath"},
		{type: "", plain: "でんき", english: "elecrticity"},
		{type: "", plain: "きょうかしょ", english: "textbook"},
		{type: "", plain: "つぎ", english: "next"},
		{type: "", plain: "あさって", english: "the day after tomorrow"},
		{type: "", plain: "おととい", english: "the day before yesterday"},
		{type: "", plain: "らいげつ", english: "next month"},
		{type: "", plain: "こんげつ", english: "this month"},
		{type: "", plain: "せんげつ", english: "last month"},
		{type: "", plain: "らいねん", english: "next year"},
		{type: "", plain: "ことし", english: "this year"},
		{type: "", plain: "きょねん", english: "last year"},
		{type: "", plain: "すごく", english: "extremely"},
		{type: "", plain: "どんな", english: "what kind of"},
		{type: "", plain: "だいじょうぶ", english: "Its' okay; no worries; everything is under control"},
		{type: "", plain: "とても", english: "very"},
		{type: "", plain: "すぐ", english: "right away"},
		{type: "", plain: "けっこうです", english: "That wouldn't be necessary."},
		{type: "", plain: "〜まい", english: "[counter for thin, flat objects]"},
		{type: "", plain: "〜から", english: "because"},
		{type: "", plain: "ゆっくり", english: "slowly; leisurely; unhurriedly"}
	]
	},
	{
	semester: "fall 2017", 
	module: "4.3",
	vocab: [
		{type: "verb", plain: "およぐ", english: "to swim"},
		{type: "verb", plain: "きく", english: "to ask"},
		{type: "verb", plain: "あそぶ", english: "to play; to spend time pleasantly"},
		{type: "verb", plain: "はいる", english: "to enter"},
		{type: "verb", plain: "けす", english: "to turn off; to erase"},
		{type: "verb", plain: "すわる", english: "to sit down"},
		{type: "verb", plain: "たばこをすう", english: "to smoke"},
		{type: "verb", plain: "てつだう", english: "to help"},
		{type: "verb", plain: "あるく", english: "to walk"},
		{type: "verb", plain: "やすむ", english: "1) to be absent from 2) to rest"},
		{type: "verb", plain: "のる", english: "to ride; to board"},
		{type: "verb", plain: "やる", english: "to do; to perform"},
		{type: "verb", plain: "いそぐ", english: "to hurry"},
		{type: "verb", plain: "かえす", english: "to return (a thing)"},
		{type: "verb", plain: "しぬ", english: "to die"},
		{type: "verb", plain: "つかう", english: "to use"},
		{type: "verb", plain: "もつ", english: "to carry; to hold"},
		{type: "verb", plain: "はしる", english: "to run"},
		{type: "verb", plain: "でかける", english: "to go out"},
		{type: "verb", plain: "おしえる", english: "to teach; to instruct"},
		{type: "verb", plain: "かりる", english: "to borrow"},
		{type: "verb", plain: "つける", english: "to turn on"},
		{type: "verb", plain: "わすれる", english: "to forget"},
		{type: "verb", plain: "あける", english: "to open (something)"},
		{type: "verb", plain: "おりる", english: "to get off"},
		{type: "verb", plain: "でんわをかける", english: "to make a phone call"},
		{type: "verb", plain: "つれてくる", english: "to bring (a person)"},
		{type: "verb", plain: "もってくる", english: "to bring (a thing)"},
		{type: "verb", plain: "たつ", english: "to stand up"},
		{type: "verb", plain: "しめる", english: "to close"}
	]
	},
	{
	semester: "winter 2017", 
	module: "1.1",
	vocab: [
		{type: "", plain: "うた", english: "song"},
		{type: "", plain: "かいしゃ", english: "company"},
		{type: "", plain: "めがね", english: "eye-glasses"},
		{type: "", plain: "じゅく", english: "cram school"},
		{type: "", plain: "しょくどう", english: "cafeteria; dining commons"},
		{type: "", plain: "サークル", english: "club activity"},
		{type: "", plain: "ごかぞく", english: "somebody else's family"},
		{type: "", plain: "かぞく", english: "your own family"},
		{type: "", plain: "ごりょうしん", english: "somebody else's parents"},
		{type: "", plain: "りょうしん", english: "your own parents"},
		{type: "", plain: "おとうさん", english: "somebody else's father"},
		{type: "", plain: "ちち", english: "your own father"},
		{type: "", plain: "おかあさん", english: "somebody else's mother"},
		{type: "", plain: "はは", english: "your own mother"},
		{type: "", plain: "ごきょうだい", english: "somebody else's siblings"},
		{type: "", plain: "きょうだい", english: "your own siblings"},
		{type: "", plain: "おにいさん", english: "somebody else's older brother"},
		{type: "", plain: "あに", english: "your own older brother"},
		{type: "", plain: "おねえさん", english: "somebody else's older sister"},
		{type: "", plain: "あね", english: "your own older sister"},
		{type: "", plain: "おとうとさん", english: "somebody else's younger brother"},
		{type: "", plain: "おとうと", english: "your own younger brother"},
		{type: "", plain: "いもうとさん", english: "somebody else's younger sister"},
		{type: "", plain: "いもうと", english: "your own younger sister"},
		{type: "", plain: "おじいさん", english: "somebody else's grandfather"},
		{type: "", plain: "そふ", english: "your own grandfather"},
		{type: "", plain: "おばあさん", english: "somebody else's grandmother"},
		{type: "", plain: "そぼ", english: "your own grandemother"},
		{type: "", plain: "おじさん", english: "somebody else's uncle"},
		{type: "", plain: "おじ", english: "your own uncle"},
		{type: "", plain: "おばさん", english: "somebody else's aunt"},
		{type: "", plain: "おば", english: "your own aunt"},
		{type: "", plain: "ひとり", english: "one person"},
		{type: "", plain: "ふたり", english: "two persons"},
		{type: "", plain: "さんにん", english: "three persons"},
		{type: "", plain: "よにん", english: "four persons"},
		{type: "", plain: "ごにん", english: "five persons"},
		{type: "", plain: "なんにん", english: "how many people?"},
		{type: "", plain: "いっぴき", english: "one small animal"},
		{type: "", plain: "にひき", english: "two small animals"},
		{type: "", plain: "さんびき", english: "three small animals"},
		{type: "", plain: "ごひき", english: "five small animals"},
		{type: "", plain: "よんひき", english: "four small animals"},
		{type: "", plain: "なんびき", english: "how many small animas?"}
	]
	},
	{
	semester: "winter 2017", 
	module: "1.2",
	vocab: [
		{type: "", plain: "かみ", english: "hair"},
		{type: "", plain: "くち", english: "mouth"},
		{type: "", plain: "め", english: "eyes"},
		{type: "", plain: "はな", english: "nose"},
		{type: "", plain: "は", english: "tooth; teeth"},
		{type: "", plain: "あし", english: "legs; feet"},
		{type: "", plain: "あたま", english: "head"},
		{type: "", plain: "かお", english: "face"},
		{type: "", plain: "からだ", english: "body"},
		{type: "verb", plain: "うたう", english: "to sing (a song)"},
		{type: "verb", plain: "かぶる", english: "to put on (a hat)"},
		{type: "verb", plain: "しる", english: "to get to know"},
		{type: "verb", plain: "すむ", english: "to live"},
		{type: "verb", plain: "はく", english: "to put on (items below your waist)"},
		{type: "verb", plain: "ふとる", english: "to gain weight"},
		{type: "verb", plain: "とる", english: "to take (a class/grade)"},
		{type: "verb", plain: "めがねをかける", english: "to put on glasses"},
		{type: "verb", plain: "きる", english: "to put on (clothes above your waist)"},
		{type: "verb", plain: "つとめる", english: "to work for"},
		{type: "verb", plain: "やせる", english: "to lose weight"},
		{type: "verb", plain: "けっこんする", english: "to get married"},
		{type: "", plain: "なにも+negative", english: "not...anything"},
		{type: "", plain: "もしもし", english: "Hello? (on the phone)"},
		{type: "", plain: "よかったら", english: "if you like"},
		{type: "", plain: "べつに+negative", english: "nothing in particular"},
		{type: "", plain: "もちろん", english: "of course"},
		{type: "", plain: "あたまがいい", english: "bright; smart; clever"},
		{type: "", plain: "かわいい", english: "cute"},
		{type: "", plain: "せがたかい", english: "tall (stature) *せ is height."},
		{type: "", plain: "せがひくい", english: "short (stature)"},
		{type: "", plain: "ながい", english: "long (length)"},
		{type: "", plain: "みじかい", english: "short (length)"},
		{type: "", plain: "はやい", english: "fast (speed)"},
		{type: "", plain: "しんせつ", english: "kind"},
		{type: "", plain: "だめ", english: "no good"},
		{type: "", plain: "べんり", english: "convenient"}
	]
	},
	{
	semester: "winter 2017", 
	module: "2.1",
	vocab: [
		{type: "", plain: "（あめが）ふる", english: "it rains"},
		{type: "verb", plain: "あらう", english: "to wash"},
		{type: "verb", plain: "いう", english: "to say"},
		{type: "verb", plain: "いる", english: "to need"},
		{type: "verb", plain: "おそくなる", english: "to be late"},
		{type: "verb", plain: "おもう", english: "to think"},
		{type: "verb", plain: "きる", english: "to cut"},
		{type: "verb", plain: "つくる", english: "to make"},
		{type: "verb", plain: "もっていく", english: "to take (a thing)"},
		{type: "verb", plain: "じろじろみる", english: "to stare at"},
		{type: "verb", plain: "すてる", english: "to throw away"},
		{type: "verb", plain: "こたえる", english: "to answer (a question)"},
		{type: "verb", plain: "はじめる", english: "to start"},
		{type: "verb", plain: "つかれる", english: "to get tired"},
		{type: "verb", plain: "つかれている", english: "to be tired"},
		{type: "verb", plain: "うんてんする", english: "to drive"},
		{type: "verb", plain: "せんたくする", english: "to do laundry"},
		{type: "verb", plain: "そうじする", english: "to get clean"},
		{type: "verb", plain: "でんわする", english: "to call"},
		{type: "verb", plain: "りょうりする", english: "to cook"},
		{type: "verb", plain: "しごと(を)する", english: "to work; to do job"},
		{type: "verb", plain: "しつもんする", english: "to ask a question"},
		{type: "verb", plain: "もってくる", english: "to bring (a thing)"},
		{type: "", plain: "ゆうめい", english: "famous"},
		{type: "", plain: "じょうず", english: "skillful; good at (objective)"},
		{type: "", plain: "へた", english: "clumsy; poor at (objective)"},
		{type: "", plain: "とくい", english: "skillful; good at (subjective)"},
		{type: "", plain: "にがて", english: "poor at; bad at (subjective)"},
		{type: "", plain: "Nounについて", english: "about...; concerning..."},
		{type: "", plain: "まだ+negative", english: "not...yet"},
		{type: "", plain: "いつも", english: "always"},
		{type: "", plain: "かんぱい", english: "cheers (a toast)"},
		{type: "", plain: "ううん", english: "no (casual)"},
		{type: "", plain: "うん", english: "yes (casual)"},
		{type: "", plain: "ざんねんですね", english: "That's too bad"},
		{type: "", plain: "みんなで", english: "all (of the people) together"}
	]
	},
	{
	semester: "winter 2017", 
	module: "2.2",
	vocab: [
		{type: "", plain: "はる", english: "spring"},
		{type: "", plain: "なつ", english: "summer"},
		{type: "", plain: "あき", english: "fall"},
		{type: "", plain: "ふゆ", english: "winter"},
		{type: "", plain: "てんきよほう", english: "weather forecast"},
		{type: "", plain: "あめ", english: "rain"},
		{type: "", plain: "はれ", english: "fair weather, sunny (sky)"},
		{type: "", plain: "くもり", english: "cloudy weather"},
		{type: "", plain: "ゆき", english: "snow"},
		{type: "", plain: "* ゆきがふる", english: "it snows"},
		{type: "", plain: "けさ", english: "this morning"},
		{type: "", plain: "ところ", english: "place"},
		{type: "", plain: "くうき", english: "air"},
		{type: "", plain: "こんげつ", english: "this month"},
		{type: "", plain: "せんげつ", english: "last month"},
		{type: "", plain: "らいげつ", english: "next month"},
		{type: "", plain: "まいしゅう", english: "every week"},
		{type: "", plain: "まいつき", english: "every month"},
		{type: "", plain: "まいとし", english: "every year* まいねん"},
		{type: "", plain: "あさって", english: "the day after tomorrow"},
		{type: "", plain: "おととい", english: "the day before yesterday"},
		{type: "", plain: "かいしゃいん", english: "office worker"},
		{type: "", plain: "しごと", english: "job; work; occupation"},
		{type: "", plain: "(お)はし", english: "chopsticks"},
		{type: "", plain: "こくばん", english: "blackboard"},
		{type: "", plain: "なにか", english: "something"},
		{type: "", plain: "こたえ", english: "answer"},
		{type: "", plain: "カメラ", english: "camera"},
		{type: "", plain: "カラオケ", english: "karaoke"},
		{type: "", plain: "パーティー", english: "party"},
		{type: "", plain: "ルームメイト", english: "roommate"},
		{type: "", plain: "ホームステイ", english: "homestay; living with a local family"},
		{type: "", plain: "ホストファミリー", english: "host family"},
		{type: "", plain: "ビール", english: "beer"},
		{type: "", plain: "キャンプ", english: "camp"}
	]
	},
	{
	semester: "winter 2017", 
	module: "3.1",
	vocab: [
		{type: "", plain: "あおい", english: "blue"},
		{type: "", plain: "あかい", english: "red"},
		{type: "", plain: "くろい", english: "black"},
		{type: "", plain: "しろい", english: "white"},
		{type: "", plain: "きいろい", english: "yellow"},
		{type: "", plain: "ちゃいろい", english: "brown"},
		{type: "", plain: "みどり", english: "green"},
		{type: "", plain: "むらさき", english: "purple"},
		{type: "", plain: "おどる", english: "to dance"},
		{type: "", plain: "おわる", english: "something ends, to end something"},
		{type: "", plain: "はじまる", english: "something begins"},
		{type: "verb", plain: "にんきがある", english: "to be popular"},
		{type: "verb", plain: "もらう", english: "to get (from somebody)"},
		{type: "verb", plain: "ひく", english: "to play string instruments"},
		{type: "verb", plain: "ふく", english: "to play wind instruments"},
		{type: "verb", plain: "たたく", english: "to play percussion instruments"},
		{type: "verb", plain: "おぼえる", english: "to memorize"},
		{type: "verb", plain: "（に）でる", english: "to appear to attend"},
		{type: "verb", plain: "（を）でる", english: "to exit"},
		{type: "verb", plain: "うんどうする", english: "to do physical exercises"},
		{type: "verb", plain: "はなしをする", english: "to tell a story, to have a talk"},
		{type: "", plain: "いじわる", english: "mean-spirited"},
		{type: "", plain: "いろいろな", english: "various"},
		{type: "", plain: "さびしい", english: "lonley"},
		{type: "", plain: "わかい", english: "young"}
	]
	},
	{
	semester: "winter 2017", 
	module: "3.2",
	vocab: [
		{type: "", plain: "ひとつ", english: "one"},
		{type: "", plain: "ふたつ", english: "two"},
		{type: "", plain: "みっつ", english: "three"},
		{type: "", plain: "よっつ", english: "four"},
		{type: "", plain: "いつつ", english: "five"},
		{type: "", plain: "むっつ", english: "six"},
		{type: "", plain: "ななつ", english: "seven"},
		{type: "", plain: "やっつ", english: "eight"},
		{type: "", plain: "ここのつ", english: "nine"},
		{type: "", plain: "とお", english: "ten"},
		{type: "", plain: "いくつ", english: "how many"},
		{type: "", plain: "いいこ", english: "good child"},
		{type: "", plain: "いろ", english: "color"},
		{type: "", plain: "おべんとう", english: "boxed lunch"},
		{type: "", plain: "かしゅ", english: "singer"},
		{type: "", plain: "ギター", english: "guitar"},
		{type: "", plain: "くすり", english: "medicine"},
		{type: "", plain: "コンサート", english: "concert"},
		{type: "", plain: "こんど", english: "next time"},
		{type: "", plain: "さくぶん", english: "essay; composition"},
		{type: "", plain: "しけん", english: "exam"},
		{type: "", plain: "スキー", english: "ski"},
		{type: "", plain: "たんご", english: "word; vocabulary"},
		{type: "", plain: "にっき", english: "diary; journal"},
		{type: "", plain: "はなし", english: "story"},
		{type: "", plain: "びょうき", english: "illness; sickness"},
		{type: "", plain: "ピアノ", english: "piano"},
		{type: "", plain: "ぜひ", english: "by all means"},
		{type: "", plain: "みんな", english: "all"},
		{type: "", plain: "ところで", english: "by the way"}
	]
	},
	{
	semester: "winter 2017", 
	module: "4.1",
	vocab: [
		{type: "verb", plain: "かかる", english: "to take (amount of time/money)"},
		{type: "verb", plain: "とまる", english: "to stay (at a hotel, etc)"},
		{type: "verb", plain: "うる", english: "to sell"},
		{type: "verb", plain: "はらう", english: "to pay"},
		{type: "verb", plain: "なる", english: "to become"},
		{type: "verb", plain: "としをとる", english: "to age"},
		{type: "verb", plain: "うそをつく", english: "to tell a lie"},
		{type: "verb", plain: "ならう", english: "to learn"},
		{type: "verb", plain: "おなかがすく", english: "to become hungry"},
		{type: "verb", plain: "のぼる", english: "to climb"},
		{type: "verb", plain: "かう", english: "to own (a pet)"},
		{type: "verb", plain: "はたらく", english: "to work"},
		{type: "verb", plain: "サボる", english: "to cut (classes)"},
		{type: "verb", plain: "きめる", english: "to decide"},
		{type: "verb", plain: "やめる", english: "to quit"},
		{type: "verb", plain: "うける", english: "to take a test, quiz, exam, etc."},
		{type: "verb", plain: "りょこうする", english: "to travel"},
		{type: "verb", plain: "よやくする", english: "to make a reservation"},
		{type: "verb", plain: "れんしゅうする", english: "to practice"},
		{type: "verb", plain: "けんかする", english: "to have a fight; to quarrel"},
		{type: "verb", plain: "しょうかいする", english: "to introduce"},
		{type: "verb", plain: "ちこくする", english: "to be late"},
		{type: "verb", plain: "ダイエットする", english: "to go on a diet"},
		{type: "verb", plain: "りゅうがくする", english: "to study abroad"},
		{type: "", plain: "あたたかい", english: "warm"},
		{type: "", plain: "ねむい", english: "sleepy"},
		{type: "", plain: "すずしい", english: "cool (temperature; not for things)"},
		{type: "", plain: "おそい", english: "slow; late"},
		{type: "", plain: "あかるい", english: "bright; well-lighted; cheerful"},
		{type: "", plain: "ちかい", english: "near; close"}
	]
	},
	{
	semester: "winter 2017", 
	module: "4.2",
	vocab: [
		{type: "", plain: "きせつ", english: "season"},
		{type: "", plain: "おしょうがつ", english: "New Year's Day"},
		{type: "", plain: "おまつり", english: "festival"},
		{type: "", plain: "じんじゃ", english: "shrine"},
		{type: "", plain: "おんせん", english: "spa; hot spring"},
		{type: "", plain: "みずうみ", english: "lake"},
		{type: "", plain: "びよういん", english: "beauty parlor"},
		{type: "", plain: "びじゅつかん", english: "art museum"},
		{type: "", plain: "しょうらい", english: "future"},
		{type: "", plain: "ゆめ", english: "dream"},
		{type: "", plain: "しゃちょう", english: "president of a company"},
		{type: "", plain: "いしゃ", english: "medical doctor"},
		{type: "", plain: "おかねもち", english: "rich person"},
		{type: "", plain: "ゆうめいじん", english: "celebrity"},
		{type: "", plain: "しゅみ", english: "hobby"},
		{type: "", plain: "やきゅう", english: "baseball"},
		{type: "", plain: "ちかてつ", english: "subway"},
		{type: "", plain: "しんかんせん", english: "bullet train"},
		{type: "", plain: "えき", english: "station"},
		{type: "", plain: "ふね", english: "ship; boat"},
		{type: "", plain: "ひこうき", english: "airplane"},
		{type: "", plain: "おかし", english: "snacks; sweets"},
		{type: "", plain: "ぎゅうにゅう", english: "milk"},
		{type: "", plain: "ケーキ", english: "cake"},
		{type: "", plain: "てんぷら", english: "tempura"},
		{type: "", plain: "りんご", english: "apple"},
		{type: "", plain: "がっき", english: "semester"},
		{type: "", plain: "こんがっき", english: "this semester"},
		{type: "", plain: "せんがっき", english: "last semester"},
		{type: "", plain: "らいがっき", english: "next semester"},
		{type: "", plain: "クレジットカード", english: "credit card"},
		{type: "", plain: "てぶくろ", english: "gloves"},
		{type: "", plain: "せかい", english: "world"},
		{type: "", plain: "せいかつ", english: "life; living"},
		{type: "", plain: "よやく", english: "reservation"},
		{type: "", plain: "みち", english: "road; way"},
		{type: "", plain: "じぶん", english: "oneself"}
	]
	},
	{
	semester: "winter 2017", 
	module: "5.1",
	vocab: [
		{type: "verb", plain: "かぜをひく", english: "to catch a cold"},
		{type: "verb", plain: "ねつがある", english: "to have a fever"},
		{type: "verb", plain: "きょうみがある", english: "to be interested in"},
		{type: "verb", plain: "のどがかわく", english: "to become thirsty"},
		{type: "verb", plain: "なくす", english: "to lose"},
		{type: "verb", plain: "せきがでる", english: "to cough"},
		{type: "verb", plain: "わかれる", english: "to break up; to separate"},
		{type: "verb", plain: "がんばる", english: "to do one's best; try hard"},
		{type: "verb", plain: "なく", english: "to cry"},
		{type: "verb", plain: "きんちょうする", english: "to get nervous"},
		{type: "verb", plain: "しんぱいする", english: "to worry"},
		{type: "verb", plain: "けがをする", english: "to get injured"},
		{type: "verb", plain: "かんどうする", english: "to be moved/touched"},
		{type: "", plain: "あまい", english: "sweet"},
		{type: "", plain: "からい", english: "spicy"},
		{type: "", plain: "せまい", english: "narrow; not spacious"},
		{type: "", plain: "ひろい", english: "spacious; broad; wide"},
		{type: "", plain: "いたい", english: "hurt; painful"},
		{type: "", plain: "わるい", english: "bad"},
		{type: "", plain: "かゆい", english: "itchy"},
		{type: "", plain: "つごうがわるい", english: "inconvenient; to have a scheduling conflict"},
		{type: "", plain: "おおい", english: "there are many..."},
		{type: "", plain: "きもちがわるい", english: "feel sick; nausea"},
		{type: "", plain: "きびしい", english: "strict"},
		{type: "", plain: "からだにいい", english: "good for health"},
		{type: "", plain: "うれしい", english: "glad"},
		{type: "", plain: "かなしい", english: "sad"},
		{type: "", plain: "すてき", english: "nice"},
		{type: "", plain: "しあわせ", english: "happy (lasting happiness)"}
		]
	},
	{
	semester: "winter 2017", 
	module: "5.2",
	vocab: [
		{type: "", plain: "おなか", english: "stomach"},
		{type: "", plain: "のど", english: "throat"},
		{type: "", plain: "は", english: "tooth"},
		{type: "", plain: "かぜ", english: "cold"},
		{type: "", plain: "せき", english: "cough"},
		{type: "", plain: "ふつかよい", english: "hangover"},
		{type: "", plain: "ホームシック", english: "homesickness"},
		{type: "", plain: "アレルギー", english: "allergy"},
		{type: "", plain: "いみ", english: "meaning"},
		{type: "", plain: "ふく", english: "clothes"},
		{type: "", plain: "はな", english: "flower"},
		{type: "", plain: "プレゼント", english: "present"},
		{type: "", plain: "かのじょ", english: "girlfriend"},
		{type: "", plain: "かれ", english: "boyfriend"},
		{type: "", plain: "もの", english: "thing (concrete object)"},
		{type: "", plain: "ようじ", english: "business to take care of"},
		{type: "", plain: "みせ", english: "shop; store"},
		{type: "", plain: "せいじ", english: "politics"},
		{type: "", plain: "しあい", english: "match; game"},
		{type: "", plain: "きおん", english: "temperature (weather-not sued for things)"},
		{type: "", plain: "おてあらい", english: "restroom"},
		{type: "", plain: "せいせき", english: "grade (on a test, etc.)"},
		{type: "", plain: "ひとびと", english: "people"},
		{type: "", plain: "かみさま", english: "God"},
		{type: "", plain: "むかし", english: "ancient times"},
		{type: "", plain: "むかしむかし", english: "once upon a time"},
		{type: "", plain: "おだいじに", english: "Get well soon."},
		{type: "", plain: "〜ど", english: "degrees (temperature)"},
		{type: "", plain: "げんきがない", english: "don't look well"},
		{type: "", plain: "にさんにち", english: "for two to three days"},
		{type: "", plain: "たぶん", english: "probably; maybe"},
		{type: "", plain: "はじめて", english: "for the first time"},
		{type: "", plain: "できるだけ", english: "as much as possible"},
		{type: "", plain: "もうすぐ", english: "very soon; in a few moments/days"},
		{type: "", plain: "じつは", english: "as a matter of fact"},
		{type: "", plain: "ぜんぶ", english: "all"},
		{type: "", plain: "〜でしょう", english: "probably..., right?"},
		{type: "", plain: "〜たち", english: "plural marker attached to personal pronouns or to human nouns"}
		]
	}
]
// console.log(vocab)
